# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-31 18:45
from __future__ import unicode_literals

import apps.volontulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontulo', '0017_remove_offer_recruitment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.volontulo.models.upload_to_organizations),
        ),
    ]
